# Generated by Django 3.0.3 on 2020-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('phone', models.IntegerField(default=15)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
